### PR TITLE
Fix/twtg corrected ts vs device profile

### PR DESCRIPTION
**Pull request by twtgrd**
@mostafaibr as discussed hereby the corrections to the VS/TS models.

There are small updates for TT and VB as well.

Note that some device models have profiles with two different LoRaWAN versions as it depends on the firmware which LoRaWAN version is used.

### CODE REVIEW

**Comment by mostafaibr** [comment]
> @mostafaibr as discussed hereby the corrections to the VS/TS models.
> 
> There are small updates for TT and VB as well.
> 
> Note that some device models have profiles with two different LoRaWAN versions as it depends on the firmware which LoRaWAN version is used.

Hello @twtgrd , thank you for the updates. Following our discussion, I have reviewed the changes, and it seems better now. 

For the several device profiles, it is accepted as you listed the device profiles IDs in the model.yaml. No problem. 

Will merge your PR and your device profiles will be updated very soon on our platforms.

**Review by mostafaibr — APPROVED** [review]

**Comment by mostafaibr** [comment]
hello @martinichka ,

We have updated your  devices on our platforms. However, our client is confused about the model to use and the compatible device profile. 
In your modifications which are already merged, you used the two profiles 1.0.2 and 1.0.4 for the same model. However, as I understood, there is two different firmware versions (each one is compatible with a lorawan version). 
So the what should be done here, is to create two "models", one per firmware (As described in the template, section versioning). Thus, for each model you specify the profiles associated to it. 
Is the new firmware can be called v2? or how do you make the difference between the two models when sharing with your clients?

**Comment by twtgrd** [comment]
Hi Mostafa,

Yes, for VB and TT v2.x.y firmware contains the LoRaWAN 1.0.4 stack and
v1.x.y contains the LoRaWAN 1.0.2 stack

So if that means two models need to be created that is fine for me. Can you
make a (example) pull request on how you want to have it?

Currently the firmware version and thus the LoRaWAN stack can be determined
from the device type on the device. For example:

   - DS-TT-01-xx has now firmware version v1.1.8, which means  LoRaWAN
   1.0.2 stack
   - DS-TT-02-xx has now firmware version v2.0.2, which means  LoRaWAN
   1.0.4 stack
   - DS-LD-01-xx has now firmware version v1.2.8, which means  LoRaWAN
   1.0.2 stack
   - DS-LD-02-xx has now firmware version v2.2.1, which means  LoRaWAN
   1.0.4 stack

But via FUOTA it is possible to load the new firmware with the LoRaWAN
1.0.4 stack on any of the devices.

Best regards,
Marten

**Comment by mostafaibr** [comment]
hello @martinichka @twtgrd ,

I have updated the devices directly on the main branch, please have a look on this commit: https://github.com/actility/device-catalog/commit/37184f265b95a0d0b20c05e9130b05107cf0c08f

Thank you for your help. 
Mostafa

**Pull request merged**
