### PR TITLE
Added new vendor: honeywell

### PR DESCRIPTION
**Pull request by rlatif97**
This is the first pull request which includes HVT driver of R100 release. 
HVT firmware version: 1.0.46

### CODE REVIEW

**Comment by mostafaibr** [comment]
Hello @rlatif97 , before reviewing your PR in details. We just noticed that "honeywell" and "elster" are the same. Is that true or we misunderstood? 
If this is the case, better to add the model and driver under the "elster" vendor which we already have in our catalog: https://github.com/actility/device-catalog/tree/main/vendors/elster.

**Comment by rlatif97** [comment]
Hello @mostafaibr , Thanks for the heads up! let me check internally what would be better to do i.e. create a new vendor under Honeywell or merge it with elster. 
You are right about that honeywell and elster are same. I do not know which of the colleagues handles the other part of the sensors.

**Comment by rlatif97** [comment]
Could we do something like honeywell as main vendor and we can move elster under honeywell? and then also integrate these?

**Comment by mostafaibr** [comment]
Sure. However, even if the "elster" vendor removed from this github repo, it will still be available on our Thingpark for sometime beside the "honeywell" for backward compatibility if some users were using it. 
Let me know if that is OK for you and I will do the necessary updates.

**Comment by rlatif97** [comment]
Yes please lets do like that.

**Pull request closed without merging**
