### PR TITLE
TXIF-2835 - Adding examples and sensors to Cicicom Parking Sensor S-LG-I3 model

### PR DESCRIPTION
**Pull request by tomHallActility**

### CODE REVIEW

**Comment by GiorgosM1995** [comment]
Payload after reset (Boot payload)  : 5230332e36362b33302e3056312e342e30 , 5231332e36362b33302e3056312e342e30
Occupation Status Change : 4330 , 4331
Status Report(Keep-Alive) : 4B30332E35352B32322E30 , 4B31332E35352B32322E30
Device Malfunction Payload : 45332E3535112233

**Comment by tomHallActility** [comment]
Hello Giorgos,

Thank you for these additional paylaod examples.

Device Malfunction Payload : 45332E3535112233
This payload, through your decoder, gives me the following data output:
          "batteryVoltage": "3.55V",
          "messageType": "Malfunction",
          "statusReport": "◄\"3"

Is it the expected statusReport value?

**Comment by tomHallActility** [comment]
Ok, thank you.
Can you tell me which bytes correspond to the status report so I can change the characters, please? (Testing is slightly blocked because of these special characters for now)
Thank you in advance.

**Comment by GiorgosM1995** [comment]
Both of the payloads


Best Regards



Georgios Mouratidis

IoT Engineer

[cid:316a7808-b24a-46e0-afc1-c46beddd664e]

Kosta Varnali 12

15233 Chalandri, Athens, Greece

Tel: +30 210 6391072 (Ext. 650)

Email: ***@***.******@***.***> | Web: www.cicicom.gr<http://www.cicicom.gr/>



[cid:38d80984-48aa-4038-95b9-4bfd752ada0f]

This e-mail (including any attached documents) is proprietary and confidential and may contain legally privileged information. It is intended for the named recipient(s) only. If you are not the intended recipient, you may not review, retain, copy or distribute this message, and we kindly ask you to notify the sender by reply e-mail immediately and delete this message from your system. Thank you.

E-mail is susceptible to unauthorized alterations which may corrupt the message of the e-mail. Our Company only sends and receives e-mails on the basis that is not liable for any unauthorized alterations made to the e-mails.

________________________________
Από: tomHallActility ***@***.***>
Στάλθηκε: Τρίτη, 9 Απριλίου 2024 5:26 μμ
Προς: actility/device-catalog ***@***.***>
Κοιν.: George Mouratidis ***@***.***>; Mention ***@***.***>
Θέμα: Re: [actility/device-catalog] TXIF-2835 - Adding examples and sensors to Cicicom Parking Sensor S-LG-I3 model (PR #127)


Ok, thank you.
Can you tell me which bytes correspond to the status report so I can change the characters, please? (Testing is slightly blocked because of these special characters for now)
Thank you in advance.

**Comment by GiorgosM1995** [comment]
Yes you can leave it like this Malfunction Payload : 45332E3535

**Review by GiorgosM1995 — APPROVED** [review]

**Review by mostafaibr — APPROVED** [review]

**Pull request merged**
