### PR TITLE
Flashnet new device profiles

### PR DESCRIPTION
**Pull request by bzalex**

### CODE REVIEW

**Review by tomHallActility — CHANGES_REQUESTED** [review]
Hi bzalex,

Thank you for making this pull request.
There are some things I will need to change after merging this branch, but first, may I ask  you if you need to provide more detailed descriptions for your models, please? It would help potential users to understand the functionalities of your devices better.
Also, it would be much appreciated if you could add datasheet URLs and user guide URLs.

Thank you very much,
Tom

**Comment by bzalex** [comment]
Hi Tom,

Thank you for your review. Please recheck.

Regards,
Alex

**Review by tomHallActility — APPROVED** [review]
Hi bzalex,

Thank you for providing this information.
It still needs some quick changes, but I'll take care of it.

Cheers,
Tom

**Comment by tomHallActility** [comment]
Hi @bzalex,

One last question.
Do you confirm that the supported LoRaWAN version for the FRE220 is 1.0.4 and not 1.0.0/1.0.1?
Or do some devices still use to use 1.0.0?
Thank you in advance.

Best regards,
Tom

**Comment by bzalex** [comment]
Some devices are still using 1.0.0

Alex

**Comment by tomHallActility** [comment]
Thank you.
As we are planning a technical improvement, we had to revert the branch.
However the modifications are ready and we will push them once done.

Best regards,
Tom

**Comment by tomHallActility** [comment]
Hi @bzalex ,

I hope you are doing well.
We are finally about to add your Flashnet model to our next catalog release tomorrow.
I just have 2 questions:

- There are 3 device models labelled FRE220. With one which seems generic. Do you want us to keep them all as they are?
- About the last device "FRE240-Zhaga", I looked online and it seems it's called FRE24-Zhaga instead. Is that correct?

Thank you in advance.

Best regards,
Tom

**Comment by bzalex** [comment]
Hi Tom,

- The generic one is the oldest device, and we keep it for compatibility.
- Indeed, the commercial name is FRE24-Zhaga, but everywhere in the technical stuff we are using the name FRE240-Zhaga.

Best regards,
Alex

**Comment by tomHallActility** [comment]
Hi Alex,

Understood, thank you very much.
Have a great day.

Best regards,
Tom

**Pull request merged**
