### PR TITLE
Added vendor Yobiiq

### PR DESCRIPTION
**Pull request by yobiiq-fostin**
Added vendor Yobiiq and its following products : 
- SD-1001
- EM2101
- EM4301
- EM4301-CT
- RM200

### CODE REVIEW

**Comment by yobiiq-fostin** [comment]
Hi @tomHallActility 
Could you please review our PR and approve it?
Thanks for your time.

**Review by tomHallActility — APPROVED** [review]
Hello Yobiiq,

Thank you for this PR. It's very carefully done.
There are 2 or 3 details I'll fix later, but I'll merge this branch.

Have a great day,
Tom

**Comment by yobiiq-fostin** [comment]
Thanks @tomHallActility 
I have a question:
Is the maximum length of the procotolId 16 characters like on ThingPark?

**Comment by yobiiq-fostin** [comment]
Great, you fixed it.
I will pay attention to this when adding new devices.

**Comment by tomHallActility** [comment]
Hi @yobiiq-fostin,
We are releasing devices and drivers, however your device profiles failed to release.
That's a problem on our side that we'll look into before the next release.
Meanwhile, we put your changes aside in a different branch (Add-yobiiq).
Thank you for your understanding.

**Comment by yobiiq-fostin** [comment]
Hi @tomHallActility 
Have you found the problem with the release of our devices?
Can you look into the following files?
- The example section of this sd-1001 model.yaml 
The example names in the model.yaml don't match the names in the sd-1001 driver examples.json
https://github.com/actility/device-catalog/blob/f656f398c17efd910f46a438ffe7bba9cb201d3d/vendors/yobiiq/models/sd-1001/model.yaml#L46
- The examples.json files also contain additional properties (`helper`) for coverage testing purposes
``` javascript
  {
    "type": "uplink",
    "description": "Device basic information",
    "input": {
      "bytes": [255, 9, 1, 0, 255, 10, 1, 0, 255, 22, 36, 1, 100, 0, 0, 255, 15, 0, 255, 11, 0],
      "fPort": 8,
      "recvTime": "2024-08-02T20:00:00.000+05:00"
    },
    "output": {
      "data": {    
        "hardwareVersion": "V1.0",
        "firmwareVersion": "V1.0",
        "deviceSerialNumber": 2401640000,
        "deviceClass": "Class A",
        "powerEvent": "AC Power Off",
        "codecVersion": "1.1.0",
        "deviceModel": "SD-1001",
        "productCode": "1002015",
        "manufacturer": "YOBIIQ B.V."
      },
      "errors": [],
      "warnings": []
    },
    "helper": {
        "function": "decodeBasicInformation"
    }
  }
```

**Comment by tomHallActility** [comment]
Hi @yobiiq-fostin 

Thank you for these clarifications.
Is it necessary to leave the helper property in the examples or can I remove them?
Also, one fatal issue with the profiles is that the 1.0.4 profile has a regionalParameterVersion of RP2-1.0.0.
And for some reason, we don't support that. Are you sure that this is the regionalParameterVersion of your devices?
Thank you in advance.

Best regards,
Tom

**Comment by yobiiq-fostin** [comment]
Hi @tomHallActility 
The regionalParameterVersion is RP2-1.0.3
You can change it.
Please leave the helper property in the examples.

**Comment by tomHallActility** [comment]
OK, thank you.
I'll leave the helper functions then.
I changed the regional parameter version to RP2-1.0.3.

**Pull request merged**
